<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="30830" started-at="2020-06-23T17:09:28Z" finished-at="2020-06-23T17:09:59Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="30830" started-at="2020-06-23T17:09:28Z" finished-at="2020-06-23T17:09:59Z">
      <class name="TestingTravels.flightSearchTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:TestingTravels.flightSearchTest@2d45ba]" name="setUp" is-config="true" duration-ms="13227" started-at="2020-06-23T17:09:28Z" finished-at="2020-06-23T17:09:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="searchForFlight()[pri:0, instance:TestingTravels.flightSearchTest@2d45ba]" name="searchForFlight" duration-ms="14" started-at="2020-06-23T17:09:41Z" finished-at="2020-06-23T17:09:41Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at TestingTravels.loginTest.logIn(loginTest.java:37)
at TestingTravels.flightSearchTest.searchForFlight(flightSearchTest.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchForFlight -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:TestingTravels.flightSearchTest@2d45ba]" name="tearDown" is-config="true" duration-ms="276" started-at="2020-06-23T17:09:41Z" finished-at="2020-06-23T17:09:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TestingTravels.flightSearchTest -->
      <class name="TestingTravels.loginTest">
        <test-method status="PASS" signature="checkingInternetConnectiity()[pri:0, instance:TestingTravels.loginTest@16905e]" name="checkingInternetConnectiity" is-config="true" duration-ms="25826" started-at="2020-06-23T17:09:02Z" finished-at="2020-06-23T17:09:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkingInternetConnectiity -->
      </class> <!-- TestingTravels.loginTest -->
      <class name="TestingTravels.userValidation">
        <test-method status="PASS" signature="setUp()[pri:0, instance:TestingTravels.userValidation@5ca609]" name="setUp" is-config="true" duration-ms="16143" started-at="2020-06-23T17:09:41Z" finished-at="2020-06-23T17:09:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="validationOfUserID()[pri:0, instance:TestingTravels.userValidation@5ca609]" name="validationOfUserID" duration-ms="1" started-at="2020-06-23T17:09:58Z" finished-at="2020-06-23T17:09:58Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at TestingTravels.loginTest.logIn(loginTest.java:37)
at TestingTravels.userValidation.validationOfUserID(userValidation.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validationOfUserID -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:TestingTravels.userValidation@5ca609]" name="tearDown" is-config="true" duration-ms="1121" started-at="2020-06-23T17:09:58Z" finished-at="2020-06-23T17:09:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TestingTravels.userValidation -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
